apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: clickhouse-secret
    creationPolicy: Owner
  data:
    - secretKey: CLICKHOUSE_PASSWORD
      remoteRef: { key: clickhouse, property: CLICKHOUSE_PASSWORD }
    - secretKey: CLICKHOUSE_MIGRATE_URL
      remoteRef: { key: clickhouse, property: CLICKHOUSE_MIGRATE_URL }
