apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-clickhouse
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ops-ahead
  source:
    repoURL: https://github.com/thiagon/ops-ahead
    targetRevision: main
    path: infra/charts/data-clickhouse
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: clickhouse.altinity.com
      kind: ClickHouseInstallation
      jqPathExpressions:
        - .spec.configuration.clusters[].layout.shards
        - .spec.configuration.clusters[].layout.replicas
        - .spec.templates.podTemplates[].metadata.labels
        - .spec.templates.podTemplates[].metadata.annotations
