apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-frontend
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ops-ahead
  source:
    repoURL: https://github.com/thiagon/ops-ahead
    targetRevision: main
    path: infra/charts/ui-frontend
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
