name: ops_ahead
version: "1.0.0"
profile: ops_ahead

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  ops_ahead:
    silver:
      +materialized: table
      +engine: "MergeTree()"
    gold:
      +materialized: table
      +engine: "MergeTree()"
    marts:
      +materialized: table
      +engine: "MergeTree()"

