ops_ahead:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DATABASE', 'default') }}"
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      secure: false
      verify: false
