apiVersion: v2
name: ops-ahead-infra
description: Ops Ahead infra namespace — ArgoCD, Vault, Gitea (dev)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: argo-cd
    version: "6.11.1"
    repository: "https://argoproj.github.io/argo-helm"
    condition: argocd.enabled
  - name: vault
    version: "0.32.0"
    repository: "https://helm.releases.hashicorp.com"
    condition: vault.enabled
  - name: gitea
    version: "10.4.1"
    repository: "https://dl.gitea.io/charts/"
    condition: gitea.enabled
