# ─── ArgoCD ──────────────────────────────────────────────────────────────────
argocd:
  enabled: true
  app:
    repoURL: https://github.com/thiagon/ops-ahead
    targetRevision: main
    path: infra/apps

argo-cd:
  server:
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicas: 1
  configs:
    params:
      server.insecure: "true"
  notifications:
    enabled: false

# ─── Vault ────────────────────────────────────────────────────────────────────
vault:
  enabled: true
  injector:
    enabled: true
  server:
    dev:
      enabled: false
    standalone:
      enabled: true
    ha:
      enabled: false
