apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef: { key: grafana, property: GRAFANA_ADMIN_USER }
    - secretKey: admin-password
      remoteRef: { key: grafana, property: GRAFANA_ADMIN_PASSWORD }
