apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: mlflow-secret
    creationPolicy: Owner
  data:
    - secretKey: MLFLOW_ADMIN_USERNAME
      remoteRef: { key: mlflow, property: MLFLOW_ADMIN_USERNAME }
    - secretKey: MLFLOW_ADMIN_PASSWORD
      remoteRef: { key: mlflow, property: MLFLOW_ADMIN_PASSWORD }
    - secretKey: MLFLOW_CRYPTO_KEK_PASSPHRASE
      remoteRef: { key: mlflow, property: MLFLOW_CRYPTO_KEK_PASSPHRASE }
    - secretKey: POSTGRES_USER
      remoteRef: { key: mlflow, property: MLFLOW_POSTGRES_USER }
    - secretKey: POSTGRES_PASSWORD
      remoteRef: { key: mlflow, property: MLFLOW_POSTGRES_PASSWORD }
    - secretKey: POSTGRES_DB
      remoteRef: { key: mlflow, property: MLFLOW_POSTGRES_DB }
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef: { key: mlflow, property: MINIO_ROOT_USER }
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef: { key: mlflow, property: MINIO_ROOT_PASSWORD }
