apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlflow
    {{- include "ml-mlflow.labels" . | nindent 4 }}
spec:
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
