{{- if gt (int .Values.mlflow.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mlflow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ml-mlflow.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mlflow
{{- end }}
