{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ml-redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
