apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-model-serving.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ml-model-serving.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "ml-model-serving.fullname" . }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.deployment.env.httpPort }}
