apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: {{ .Release.Namespace }}
  labels:
    app: litellm
    {{- include "llm-litellm.labels" . | nindent 4 }}
spec:
  selector:
    app: litellm
  ports:
    - name: http
      port: 4000
      targetPort: 4000
