apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-litellm.labels" . | nindent 4 }}
automountServiceAccountToken: false
