kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 24h
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
  alertmanager:
    enabled: true
  grafana:
    adminPassword: "ops-ahead-dev"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
