kafka:
  enabled: true
  cluster:
    replicas: 1
    storage:
      type: ephemeral
    retention:
      ms: "3600000"   # 1 hour
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 1000m
    jvmOptions:
      "-Xms": "256m"
      "-Xmx": "512m"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi

kafkaTopics:
  - name: incidents.received
    partitions: 3
    replicas: 1
    config:
      retention.ms: "86400000"    # 24 hours
  - name: incidents.scored
    partitions: 1
    replicas: 1
  - name: alerts.burst
    partitions: 1
    replicas: 1
  - name: recommendations
    partitions: 1
    replicas: 1
  - name: actions.taken
    partitions: 1
    replicas: 1
