kafka:
  cluster:
    replicas: 1
    storage:
      size: 2Gi
    retention:
      ms: "3600000"   # 1 hour
  zookeeper:
    replicas: 1
    storage:
      size: 1Gi

kafkaTopics:
  - name: incidents.raw
    partitions: 1
    replicas: 1
  - name: incidents.scored
    partitions: 1
    replicas: 1
  - name: alerts.burst
    partitions: 1
    replicas: 1
  - name: recommendations
    partitions: 1
    replicas: 1
  - name: actions.taken
    partitions: 1
    replicas: 1
