apiVersion: v2
name: infra-argocd
description: ArgoCD — GitOps engine
type: application
version: 0.1.0
appVersion: "3.4.4"
dependencies:
  - name: argo-cd
    alias: argocd
    version: "10.1.2"
    repository: "https://argoproj.github.io/argo-helm"
