argocd:
  server:
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicas: 1
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  configs:
    params:
      server.insecure: "true"
    secret:
      createSecret: false
    cm:
      server.diff.server.side: "true"
      resource.customizations.ignoreDifferences.apps_Deployment: |
        jqPathExpressions:
          - '.metadata.annotations."deployment.kubernetes.io/revision"'
      resource.customizations.ignoreDifferences.apps_DaemonSet: |
        jqPathExpressions:
          - '.metadata.annotations."deprecated.daemonset.template.generation"'
  notifications:
    enabled: false
