apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.consumer.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: {{ .Values.consumer.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: SLACK_BOT_TOKEN
      remoteRef: { key: notify-slack, property: SLACK_BOT_TOKEN }
