apiVersion: v1
kind: Service
metadata:
  name: {{ include "notify-slack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notify-slack.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "notify-slack.fullname" . }}
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
