apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.job.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: {{ .Values.job.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: CLICKHOUSE_PASSWORD
      remoteRef: { key: ml-breach-model, property: CLICKHOUSE_PASSWORD }
