apiVersion: v2
name: infra-vault
description: Vault — secrets management
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: vault
    version: "0.32.0"
    repository: "https://helm.releases.hashicorp.com"
