vault:
  ui:
    enabled: true
  server:
    dev:
      enabled: false
    standalone:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address     = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "file" {
          path = "/vault/data"
        }
    dataStorage:
      enabled: true
      storageClass: local-path
      size: 1Gi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
  injector:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
