apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-kv
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: {{ .Values.vault.address }}
      path: {{ .Values.vault.kvPath }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.vault.role }}
          serviceAccountRef:
            name: external-secrets
            namespace: infra
