apiVersion: v1
kind: Secret
metadata:
  name: mlflow-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ops-ahead-ml.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ index .Values "mlflow-postgres" "auth" "username" | quote }}
  POSTGRES_PASSWORD: {{ index .Values "mlflow-postgres" "auth" "password" | quote }}
  POSTGRES_DB: {{ index .Values "mlflow-postgres" "auth" "database" | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.mlflow.minio.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.mlflow.minio.secretKey | quote }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.mlflow.minio.endpoint | quote }}
