apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ops-ahead-ml.labels" . | nindent 4 }}
automountServiceAccountToken: false
