{{- if .Values.kafka.enabled }}
{{- range .Values.kafkaTopics }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .name | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    strimzi.io/cluster: ops-ahead
    {{- include "data-kafka.labels" $ | nindent 4 }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  topicName: {{ .name }}
  {{- if .config }}
  config:
    {{- range $k, $v := .config }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
