{{- if and .Values.kafka.enabled .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-kafka.labels" . | nindent 4 }}
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          topic: "$4"
          partition: "$5"
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          broker: "$4:$5"
      - pattern: kafka.(\w+)<type=(.+), name=(.+)><>(\w+)
        name: kafka_$1_$2_$3_$4
        type: GAUGE
      - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Count
        name: kafka_$1_$2_$3_count
        type: COUNTER
      - pattern: "kafka.server<type=raft-metrics><>(.+-total|.+-max):"
        name: kafka_server_raftmetrics_$1
        type: COUNTER
      - pattern: "kafka.server<type=raft-metrics><>(.+):"
        name: kafka_server_raftmetrics_$1
        type: GAUGE
      - pattern: ".*"
{{- end }}
