{{- if and .Values.kafka.enabled .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-kafka.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: ops-ahead
      strimzi.io/kind: Kafka
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
