apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: ui
    {{- include "ui-frontend.labels" . | nindent 4 }}
spec:
  selector:
    app: ui
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ui-frontend.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 80
