{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-minio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: minio
  endpoints:
    - port: api
      path: /minio/v2/metrics/cluster
      interval: 30s
      scrapeTimeout: 10s
    - port: api
      path: /minio/v2/metrics/node
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
